name: GitHub Jekyll Build Action
description: This action builds a Jekyll site and deploys against GHpages

branding:
  icon: 'home'
  color: 'red'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  GH_PAGES_BRANCH:
    description: 'override the default `gh-pages` deployment branch'
    required: false
    default: 'gh-pages'

  SOURCE_FOLDER:
    description: 'override the default `./` folder for sources for website'
    required: false
    default: './'
